// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/experimental/authorization_config.proto

package org.glowroot.agent.shaded.google.api;

public interface AuthorizationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.AuthorizationConfig)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>string provider = 1;</code>
   */
  java.lang.String getProvider();
  /**
   * <pre>
   * The name of the authorization provider, such as
   * firebaserules.googleapis.com.
   * </pre>
   *
   * <code>string provider = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getProviderBytes();
}
