// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/context.proto

package org.glowroot.agent.shaded.google.api;

public interface ContextRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.ContextRule)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Selects the methods to which this rule applies.
   * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
   * </pre>
   *
   * <code>string selector = 1;</code>
   */
  java.lang.String getSelector();
  /**
   * <pre>
   * Selects the methods to which this rule applies.
   * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
   * </pre>
   *
   * <code>string selector = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getSelectorBytes();

  /**
   * <pre>
   * A list of full type names of requested contexts.
   * </pre>
   *
   * <code>repeated string requested = 2;</code>
   */
  java.util.List<java.lang.String>
      getRequestedList();
  /**
   * <pre>
   * A list of full type names of requested contexts.
   * </pre>
   *
   * <code>repeated string requested = 2;</code>
   */
  int getRequestedCount();
  /**
   * <pre>
   * A list of full type names of requested contexts.
   * </pre>
   *
   * <code>repeated string requested = 2;</code>
   */
  java.lang.String getRequested(int index);
  /**
   * <pre>
   * A list of full type names of requested contexts.
   * </pre>
   *
   * <code>repeated string requested = 2;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getRequestedBytes(int index);

  /**
   * <pre>
   * A list of full type names of provided contexts.
   * </pre>
   *
   * <code>repeated string provided = 3;</code>
   */
  java.util.List<java.lang.String>
      getProvidedList();
  /**
   * <pre>
   * A list of full type names of provided contexts.
   * </pre>
   *
   * <code>repeated string provided = 3;</code>
   */
  int getProvidedCount();
  /**
   * <pre>
   * A list of full type names of provided contexts.
   * </pre>
   *
   * <code>repeated string provided = 3;</code>
   */
  java.lang.String getProvided(int index);
  /**
   * <pre>
   * A list of full type names of provided contexts.
   * </pre>
   *
   * <code>repeated string provided = 3;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getProvidedBytes(int index);
}
