// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/httpbody.proto

package org.glowroot.agent.shaded.google.api;

public interface HttpBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.HttpBody)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>string content_type = 1;</code>
   */
  java.lang.String getContentType();
  /**
   * <pre>
   * The HTTP Content-Type string representing the content type of the body.
   * </pre>
   *
   * <code>string content_type = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   * HTTP body binary data.
   * </pre>
   *
   * <code>bytes data = 2;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString getData();
}
