// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/consumer.proto

package org.glowroot.agent.shaded.google.api;

public interface ProjectPropertiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.ProjectProperties)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of per consumer project-specific properties.
   * </pre>
   *
   * <code>repeated .google.api.Property properties = 1;</code>
   */
  java.util.List<org.glowroot.agent.shaded.google.api.Property> 
      getPropertiesList();
  /**
   * <pre>
   * List of per consumer project-specific properties.
   * </pre>
   *
   * <code>repeated .google.api.Property properties = 1;</code>
   */
  org.glowroot.agent.shaded.google.api.Property getProperties(int index);
  /**
   * <pre>
   * List of per consumer project-specific properties.
   * </pre>
   *
   * <code>repeated .google.api.Property properties = 1;</code>
   */
  int getPropertiesCount();
  /**
   * <pre>
   * List of per consumer project-specific properties.
   * </pre>
   *
   * <code>repeated .google.api.Property properties = 1;</code>
   */
  java.util.List<? extends org.glowroot.agent.shaded.google.api.PropertyOrBuilder> 
      getPropertiesOrBuilderList();
  /**
   * <pre>
   * List of per consumer project-specific properties.
   * </pre>
   *
   * <code>repeated .google.api.Property properties = 1;</code>
   */
  org.glowroot.agent.shaded.google.api.PropertyOrBuilder getPropertiesOrBuilder(
      int index);
}
