// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/source_info.proto

package org.glowroot.agent.shaded.google.api;

public interface SourceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.SourceInfo)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * All files used during config generation.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any source_files = 1;</code>
   */
  java.util.List<org.glowroot.agent.shaded.google.protobuf.Any> 
      getSourceFilesList();
  /**
   * <pre>
   * All files used during config generation.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any source_files = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.Any getSourceFiles(int index);
  /**
   * <pre>
   * All files used during config generation.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any source_files = 1;</code>
   */
  int getSourceFilesCount();
  /**
   * <pre>
   * All files used during config generation.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any source_files = 1;</code>
   */
  java.util.List<? extends org.glowroot.agent.shaded.google.protobuf.AnyOrBuilder> 
      getSourceFilesOrBuilderList();
  /**
   * <pre>
   * All files used during config generation.
   * </pre>
   *
   * <code>repeated .google.protobuf.Any source_files = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.AnyOrBuilder getSourceFilesOrBuilder(
      int index);
}
