// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/system_parameter.proto

package org.glowroot.agent.shaded.google.api;

public final class SystemParameterProto {
  private SystemParameterProto() {}
  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_SystemParameters_descriptor;
  static final 
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_SystemParameters_fieldAccessorTable;
  static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_SystemParameterRule_descriptor;
  static final 
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_SystemParameterRule_fieldAccessorTable;
  static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_SystemParameter_descriptor;
  static final 
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_SystemParameter_fieldAccessorTable;

  public static org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!google/api/system_parameter.proto\022\ngoo" +
      "gle.api\"B\n\020SystemParameters\022.\n\005rules\030\001 \003" +
      "(\0132\037.google.api.SystemParameterRule\"X\n\023S" +
      "ystemParameterRule\022\020\n\010selector\030\001 \001(\t\022/\n\n" +
      "parameters\030\002 \003(\0132\033.google.api.SystemPara" +
      "meter\"Q\n\017SystemParameter\022\014\n\004name\030\001 \001(\t\022\023" +
      "\n\013http_header\030\002 \001(\t\022\033\n\023url_query_paramet" +
      "er\030\003 \001(\tBv\n\016com.google.apiB\024SystemParame" +
      "terProtoP\001ZEgoogle.golang.org/genproto/g" +
      "oogleapis/api/serviceconfig;serviceconfi",
      "g\242\002\004GAPIb\006proto3"
    };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry assignDescriptors(
              org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_api_SystemParameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_SystemParameters_fieldAccessorTable = new
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_SystemParameters_descriptor,
        new java.lang.String[] { "Rules", });
    internal_static_google_api_SystemParameterRule_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_api_SystemParameterRule_fieldAccessorTable = new
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_SystemParameterRule_descriptor,
        new java.lang.String[] { "Selector", "Parameters", });
    internal_static_google_api_SystemParameter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_api_SystemParameter_fieldAccessorTable = new
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_SystemParameter_descriptor,
        new java.lang.String[] { "Name", "HttpHeader", "UrlQueryParameter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
