// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/system_parameter.proto

package org.glowroot.agent.shaded.google.api;

/**
 * <pre>
 * Define a parameter's name and location. The parameter may be passed as either
 * an HTTP header or a URL query parameter, and if both are passed the behavior
 * is implementation-dependent.
 * </pre>
 *
 * Protobuf type {@code google.api.SystemParameter}
 */
public  final class SystemParameter extends
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.SystemParameter)
    SystemParameterOrBuilder {
  // Use SystemParameter.newBuilder() to construct.
  private SystemParameter(org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SystemParameter() {
    name_ = "";
    httpHeader_ = "";
    urlQueryParameter_ = "";
  }

  @java.lang.Override
  public final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SystemParameter(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            httpHeader_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            urlQueryParameter_ = s;
            break;
          }
        }
      }
    } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.glowroot.agent.shaded.google.api.SystemParameterProto.internal_static_google_api_SystemParameter_descriptor;
  }

  protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.glowroot.agent.shaded.google.api.SystemParameterProto.internal_static_google_api_SystemParameter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.glowroot.agent.shaded.google.api.SystemParameter.class, org.glowroot.agent.shaded.google.api.SystemParameter.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Define the name of the parameter, such as "api_key" . It is case sensitive.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Define the name of the parameter, such as "api_key" . It is case sensitive.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTTP_HEADER_FIELD_NUMBER = 2;
  private volatile java.lang.Object httpHeader_;
  /**
   * <pre>
   * Define the HTTP header name to use for the parameter. It is case
   * insensitive.
   * </pre>
   *
   * <code>string http_header = 2;</code>
   */
  public java.lang.String getHttpHeader() {
    java.lang.Object ref = httpHeader_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      httpHeader_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Define the HTTP header name to use for the parameter. It is case
   * insensitive.
   * </pre>
   *
   * <code>string http_header = 2;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getHttpHeaderBytes() {
    java.lang.Object ref = httpHeader_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      httpHeader_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_QUERY_PARAMETER_FIELD_NUMBER = 3;
  private volatile java.lang.Object urlQueryParameter_;
  /**
   * <pre>
   * Define the URL query parameter name to use for the parameter. It is case
   * sensitive.
   * </pre>
   *
   * <code>string url_query_parameter = 3;</code>
   */
  public java.lang.String getUrlQueryParameter() {
    java.lang.Object ref = urlQueryParameter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      urlQueryParameter_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Define the URL query parameter name to use for the parameter. It is case
   * sensitive.
   * </pre>
   *
   * <code>string url_query_parameter = 3;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getUrlQueryParameterBytes() {
    java.lang.Object ref = urlQueryParameter_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      urlQueryParameter_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.glowroot.agent.shaded.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getHttpHeaderBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 2, httpHeader_);
    }
    if (!getUrlQueryParameterBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 3, urlQueryParameter_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getHttpHeaderBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(2, httpHeader_);
    }
    if (!getUrlQueryParameterBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(3, urlQueryParameter_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.glowroot.agent.shaded.google.api.SystemParameter)) {
      return super.equals(obj);
    }
    org.glowroot.agent.shaded.google.api.SystemParameter other = (org.glowroot.agent.shaded.google.api.SystemParameter) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getHttpHeader()
        .equals(other.getHttpHeader());
    result = result && getUrlQueryParameter()
        .equals(other.getUrlQueryParameter());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + HTTP_HEADER_FIELD_NUMBER;
    hash = (53 * hash) + getHttpHeader().hashCode();
    hash = (37 * hash) + URL_QUERY_PARAMETER_FIELD_NUMBER;
    hash = (53 * hash) + getUrlQueryParameter().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(byte[] data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      byte[] data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseDelimitedFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.SystemParameter parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.glowroot.agent.shaded.google.api.SystemParameter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define a parameter's name and location. The parameter may be passed as either
   * an HTTP header or a URL query parameter, and if both are passed the behavior
   * is implementation-dependent.
   * </pre>
   *
   * Protobuf type {@code google.api.SystemParameter}
   */
  public static final class Builder extends
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.SystemParameter)
      org.glowroot.agent.shaded.google.api.SystemParameterOrBuilder {
    public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.shaded.google.api.SystemParameterProto.internal_static_google_api_SystemParameter_descriptor;
    }

    protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.shaded.google.api.SystemParameterProto.internal_static_google_api_SystemParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.shaded.google.api.SystemParameter.class, org.glowroot.agent.shaded.google.api.SystemParameter.Builder.class);
    }

    // Construct using org.glowroot.agent.shaded.google.api.SystemParameter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      httpHeader_ = "";

      urlQueryParameter_ = "";

      return this;
    }

    public org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.glowroot.agent.shaded.google.api.SystemParameterProto.internal_static_google_api_SystemParameter_descriptor;
    }

    public org.glowroot.agent.shaded.google.api.SystemParameter getDefaultInstanceForType() {
      return org.glowroot.agent.shaded.google.api.SystemParameter.getDefaultInstance();
    }

    public org.glowroot.agent.shaded.google.api.SystemParameter build() {
      org.glowroot.agent.shaded.google.api.SystemParameter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.glowroot.agent.shaded.google.api.SystemParameter buildPartial() {
      org.glowroot.agent.shaded.google.api.SystemParameter result = new org.glowroot.agent.shaded.google.api.SystemParameter(this);
      result.name_ = name_;
      result.httpHeader_ = httpHeader_;
      result.urlQueryParameter_ = urlQueryParameter_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.glowroot.agent.shaded.google.protobuf.Message other) {
      if (other instanceof org.glowroot.agent.shaded.google.api.SystemParameter) {
        return mergeFrom((org.glowroot.agent.shaded.google.api.SystemParameter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.glowroot.agent.shaded.google.api.SystemParameter other) {
      if (other == org.glowroot.agent.shaded.google.api.SystemParameter.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getHttpHeader().isEmpty()) {
        httpHeader_ = other.httpHeader_;
        onChanged();
      }
      if (!other.getUrlQueryParameter().isEmpty()) {
        urlQueryParameter_ = other.urlQueryParameter_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.glowroot.agent.shaded.google.api.SystemParameter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.glowroot.agent.shaded.google.api.SystemParameter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Define the name of the parameter, such as "api_key" . It is case sensitive.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Define the name of the parameter, such as "api_key" . It is case sensitive.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Define the name of the parameter, such as "api_key" . It is case sensitive.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the name of the parameter, such as "api_key" . It is case sensitive.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the name of the parameter, such as "api_key" . It is case sensitive.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object httpHeader_ = "";
    /**
     * <pre>
     * Define the HTTP header name to use for the parameter. It is case
     * insensitive.
     * </pre>
     *
     * <code>string http_header = 2;</code>
     */
    public java.lang.String getHttpHeader() {
      java.lang.Object ref = httpHeader_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpHeader_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Define the HTTP header name to use for the parameter. It is case
     * insensitive.
     * </pre>
     *
     * <code>string http_header = 2;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getHttpHeaderBytes() {
      java.lang.Object ref = httpHeader_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpHeader_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Define the HTTP header name to use for the parameter. It is case
     * insensitive.
     * </pre>
     *
     * <code>string http_header = 2;</code>
     */
    public Builder setHttpHeader(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      httpHeader_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the HTTP header name to use for the parameter. It is case
     * insensitive.
     * </pre>
     *
     * <code>string http_header = 2;</code>
     */
    public Builder clearHttpHeader() {
      
      httpHeader_ = getDefaultInstance().getHttpHeader();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the HTTP header name to use for the parameter. It is case
     * insensitive.
     * </pre>
     *
     * <code>string http_header = 2;</code>
     */
    public Builder setHttpHeaderBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      httpHeader_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object urlQueryParameter_ = "";
    /**
     * <pre>
     * Define the URL query parameter name to use for the parameter. It is case
     * sensitive.
     * </pre>
     *
     * <code>string url_query_parameter = 3;</code>
     */
    public java.lang.String getUrlQueryParameter() {
      java.lang.Object ref = urlQueryParameter_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        urlQueryParameter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Define the URL query parameter name to use for the parameter. It is case
     * sensitive.
     * </pre>
     *
     * <code>string url_query_parameter = 3;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getUrlQueryParameterBytes() {
      java.lang.Object ref = urlQueryParameter_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlQueryParameter_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Define the URL query parameter name to use for the parameter. It is case
     * sensitive.
     * </pre>
     *
     * <code>string url_query_parameter = 3;</code>
     */
    public Builder setUrlQueryParameter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      urlQueryParameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the URL query parameter name to use for the parameter. It is case
     * sensitive.
     * </pre>
     *
     * <code>string url_query_parameter = 3;</code>
     */
    public Builder clearUrlQueryParameter() {
      
      urlQueryParameter_ = getDefaultInstance().getUrlQueryParameter();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Define the URL query parameter name to use for the parameter. It is case
     * sensitive.
     * </pre>
     *
     * <code>string url_query_parameter = 3;</code>
     */
    public Builder setUrlQueryParameterBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      urlQueryParameter_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.api.SystemParameter)
  }

  // @@protoc_insertion_point(class_scope:google.api.SystemParameter)
  private static final org.glowroot.agent.shaded.google.api.SystemParameter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.glowroot.agent.shaded.google.api.SystemParameter();
  }

  public static org.glowroot.agent.shaded.google.api.SystemParameter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.glowroot.agent.shaded.google.protobuf.Parser<SystemParameter>
      PARSER = new org.glowroot.agent.shaded.google.protobuf.AbstractParser<SystemParameter>() {
    public SystemParameter parsePartialFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
        return new SystemParameter(input, extensionRegistry);
    }
  };

  public static org.glowroot.agent.shaded.google.protobuf.Parser<SystemParameter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.glowroot.agent.shaded.google.protobuf.Parser<SystemParameter> getParserForType() {
    return PARSER;
  }

  public org.glowroot.agent.shaded.google.api.SystemParameter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

