// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/audit/audit_log.proto

package org.glowroot.agent.shaded.google.cloud.audit;

/**
 * <pre>
 * Authentication information for the operation.
 * </pre>
 *
 * Protobuf type {@code google.cloud.audit.AuthenticationInfo}
 */
public  final class AuthenticationInfo extends
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.cloud.audit.AuthenticationInfo)
    AuthenticationInfoOrBuilder {
  // Use AuthenticationInfo.newBuilder() to construct.
  private AuthenticationInfo(org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthenticationInfo() {
    principalEmail_ = "";
  }

  @java.lang.Override
  public final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AuthenticationInfo(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            principalEmail_ = s;
            break;
          }
        }
      }
    } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.glowroot.agent.shaded.google.cloud.audit.AuditLogProto.internal_static_google_cloud_audit_AuthenticationInfo_descriptor;
  }

  protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.glowroot.agent.shaded.google.cloud.audit.AuditLogProto.internal_static_google_cloud_audit_AuthenticationInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.class, org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.Builder.class);
  }

  public static final int PRINCIPAL_EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object principalEmail_;
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>string principal_email = 1;</code>
   */
  public java.lang.String getPrincipalEmail() {
    java.lang.Object ref = principalEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      principalEmail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The email address of the authenticated user making the request.
   * </pre>
   *
   * <code>string principal_email = 1;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getPrincipalEmailBytes() {
    java.lang.Object ref = principalEmail_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      principalEmail_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.glowroot.agent.shaded.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPrincipalEmailBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 1, principalEmail_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPrincipalEmailBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(1, principalEmail_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo)) {
      return super.equals(obj);
    }
    org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo other = (org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo) obj;

    boolean result = true;
    result = result && getPrincipalEmail()
        .equals(other.getPrincipalEmail());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRINCIPAL_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getPrincipalEmail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(byte[] data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      byte[] data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseDelimitedFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Authentication information for the operation.
   * </pre>
   *
   * Protobuf type {@code google.cloud.audit.AuthenticationInfo}
   */
  public static final class Builder extends
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.audit.AuthenticationInfo)
      org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfoOrBuilder {
    public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.shaded.google.cloud.audit.AuditLogProto.internal_static_google_cloud_audit_AuthenticationInfo_descriptor;
    }

    protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.shaded.google.cloud.audit.AuditLogProto.internal_static_google_cloud_audit_AuthenticationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.class, org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.Builder.class);
    }

    // Construct using org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      principalEmail_ = "";

      return this;
    }

    public org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.glowroot.agent.shaded.google.cloud.audit.AuditLogProto.internal_static_google_cloud_audit_AuthenticationInfo_descriptor;
    }

    public org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo getDefaultInstanceForType() {
      return org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.getDefaultInstance();
    }

    public org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo build() {
      org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo buildPartial() {
      org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo result = new org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo(this);
      result.principalEmail_ = principalEmail_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.glowroot.agent.shaded.google.protobuf.Message other) {
      if (other instanceof org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo) {
        return mergeFrom((org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo other) {
      if (other == org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo.getDefaultInstance()) return this;
      if (!other.getPrincipalEmail().isEmpty()) {
        principalEmail_ = other.principalEmail_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object principalEmail_ = "";
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>string principal_email = 1;</code>
     */
    public java.lang.String getPrincipalEmail() {
      java.lang.Object ref = principalEmail_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        principalEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>string principal_email = 1;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getPrincipalEmailBytes() {
      java.lang.Object ref = principalEmail_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        principalEmail_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>string principal_email = 1;</code>
     */
    public Builder setPrincipalEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      principalEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>string principal_email = 1;</code>
     */
    public Builder clearPrincipalEmail() {
      
      principalEmail_ = getDefaultInstance().getPrincipalEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The email address of the authenticated user making the request.
     * </pre>
     *
     * <code>string principal_email = 1;</code>
     */
    public Builder setPrincipalEmailBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      principalEmail_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.cloud.audit.AuthenticationInfo)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.audit.AuthenticationInfo)
  private static final org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo();
  }

  public static org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.glowroot.agent.shaded.google.protobuf.Parser<AuthenticationInfo>
      PARSER = new org.glowroot.agent.shaded.google.protobuf.AbstractParser<AuthenticationInfo>() {
    public AuthenticationInfo parsePartialFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticationInfo(input, extensionRegistry);
    }
  };

  public static org.glowroot.agent.shaded.google.protobuf.Parser<AuthenticationInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.glowroot.agent.shaded.google.protobuf.Parser<AuthenticationInfo> getParserForType() {
    return PARSER;
  }

  public org.glowroot.agent.shaded.google.cloud.audit.AuthenticationInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

