// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/empty.proto

package org.glowroot.agent.shaded.google.protobuf;

public final class EmptyProto {
  private EmptyProto() {}
  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Empty_descriptor;
  static final 
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Empty_fieldAccessorTable;

  public static org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033google/protobuf/empty.proto\022\017google.pr" +
      "otobuf\"\007\n\005EmptyBv\n\023com.google.protobufB\n" +
      "EmptyProtoP\001Z\'github.com/golang/protobuf" +
      "/ptypes/empty\370\001\001\242\002\003GPB\252\002\036Google.Protobuf" +
      ".WellKnownTypesb\006proto3"
    };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry assignDescriptors(
              org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Empty_fieldAccessorTable = new
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
