// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package org.glowroot.agent.shaded.google.protobuf;

public interface UInt32ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.UInt32Value)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The uint32 value.
   * </pre>
   *
   * <code>uint32 value = 1;</code>
   */
  int getValue();
}
