// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package org.glowroot.agent.shaded.google.api.servicemanagement.v1;

/**
 * <pre>
 * Request message for CreateServiceConfig method.
 * </pre>
 *
 * Protobuf type {@code google.api.servicemanagement.v1.CreateServiceConfigRequest}
 */
public  final class CreateServiceConfigRequest extends
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.servicemanagement.v1.CreateServiceConfigRequest)
    CreateServiceConfigRequestOrBuilder {
  // Use CreateServiceConfigRequest.newBuilder() to construct.
  private CreateServiceConfigRequest(org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateServiceConfigRequest() {
    serviceName_ = "";
  }

  @java.lang.Override
  public final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateServiceConfigRequest(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 18: {
            org.glowroot.agent.shaded.google.api.Service.Builder subBuilder = null;
            if (serviceConfig_ != null) {
              subBuilder = serviceConfig_.toBuilder();
            }
            serviceConfig_ = input.readMessage(org.glowroot.agent.shaded.google.api.Service.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(serviceConfig_);
              serviceConfig_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor;
  }

  protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.Builder.class);
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceName_;
  /**
   * <pre>
   * The name of the service.  See the [overview](/service-management/overview)
   * for naming requirements.  For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the service.  See the [overview](/service-management/overview)
   * for naming requirements.  For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_CONFIG_FIELD_NUMBER = 2;
  private org.glowroot.agent.shaded.google.api.Service serviceConfig_;
  /**
   * <pre>
   * The service configuration resource.
   * </pre>
   *
   * <code>.google.api.Service service_config = 2;</code>
   */
  public boolean hasServiceConfig() {
    return serviceConfig_ != null;
  }
  /**
   * <pre>
   * The service configuration resource.
   * </pre>
   *
   * <code>.google.api.Service service_config = 2;</code>
   */
  public org.glowroot.agent.shaded.google.api.Service getServiceConfig() {
    return serviceConfig_ == null ? org.glowroot.agent.shaded.google.api.Service.getDefaultInstance() : serviceConfig_;
  }
  /**
   * <pre>
   * The service configuration resource.
   * </pre>
   *
   * <code>.google.api.Service service_config = 2;</code>
   */
  public org.glowroot.agent.shaded.google.api.ServiceOrBuilder getServiceConfigOrBuilder() {
    return getServiceConfig();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.glowroot.agent.shaded.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceNameBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (serviceConfig_ != null) {
      output.writeMessage(2, getServiceConfig());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceNameBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (serviceConfig_ != null) {
      size += org.glowroot.agent.shaded.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getServiceConfig());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest)) {
      return super.equals(obj);
    }
    org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest other = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest) obj;

    boolean result = true;
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && (hasServiceConfig() == other.hasServiceConfig());
    if (hasServiceConfig()) {
      result = result && getServiceConfig()
          .equals(other.getServiceConfig());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    if (hasServiceConfig()) {
      hash = (37 * hash) + SERVICE_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getServiceConfig().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(byte[] data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      byte[] data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for CreateServiceConfig method.
   * </pre>
   *
   * Protobuf type {@code google.api.servicemanagement.v1.CreateServiceConfigRequest}
   */
  public static final class Builder extends
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.servicemanagement.v1.CreateServiceConfigRequest)
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequestOrBuilder {
    public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor;
    }

    protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.Builder.class);
    }

    // Construct using org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serviceName_ = "";

      if (serviceConfigBuilder_ == null) {
        serviceConfig_ = null;
      } else {
        serviceConfig_ = null;
        serviceConfigBuilder_ = null;
      }
      return this;
    }

    public org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest getDefaultInstanceForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.getDefaultInstance();
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest build() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest buildPartial() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest result = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest(this);
      result.serviceName_ = serviceName_;
      if (serviceConfigBuilder_ == null) {
        result.serviceConfig_ = serviceConfig_;
      } else {
        result.serviceConfig_ = serviceConfigBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.glowroot.agent.shaded.google.protobuf.Message other) {
      if (other instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest) {
        return mergeFrom((org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest other) {
      if (other == org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (other.hasServiceConfig()) {
        mergeServiceConfig(other.getServiceConfig());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceNameBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private org.glowroot.agent.shaded.google.api.Service serviceConfig_ = null;
    private org.glowroot.agent.shaded.google.protobuf.SingleFieldBuilderV3<
        org.glowroot.agent.shaded.google.api.Service, org.glowroot.agent.shaded.google.api.Service.Builder, org.glowroot.agent.shaded.google.api.ServiceOrBuilder> serviceConfigBuilder_;
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public boolean hasServiceConfig() {
      return serviceConfigBuilder_ != null || serviceConfig_ != null;
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public org.glowroot.agent.shaded.google.api.Service getServiceConfig() {
      if (serviceConfigBuilder_ == null) {
        return serviceConfig_ == null ? org.glowroot.agent.shaded.google.api.Service.getDefaultInstance() : serviceConfig_;
      } else {
        return serviceConfigBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public Builder setServiceConfig(org.glowroot.agent.shaded.google.api.Service value) {
      if (serviceConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serviceConfig_ = value;
        onChanged();
      } else {
        serviceConfigBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public Builder setServiceConfig(
        org.glowroot.agent.shaded.google.api.Service.Builder builderForValue) {
      if (serviceConfigBuilder_ == null) {
        serviceConfig_ = builderForValue.build();
        onChanged();
      } else {
        serviceConfigBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public Builder mergeServiceConfig(org.glowroot.agent.shaded.google.api.Service value) {
      if (serviceConfigBuilder_ == null) {
        if (serviceConfig_ != null) {
          serviceConfig_ =
            org.glowroot.agent.shaded.google.api.Service.newBuilder(serviceConfig_).mergeFrom(value).buildPartial();
        } else {
          serviceConfig_ = value;
        }
        onChanged();
      } else {
        serviceConfigBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public Builder clearServiceConfig() {
      if (serviceConfigBuilder_ == null) {
        serviceConfig_ = null;
        onChanged();
      } else {
        serviceConfig_ = null;
        serviceConfigBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public org.glowroot.agent.shaded.google.api.Service.Builder getServiceConfigBuilder() {
      
      onChanged();
      return getServiceConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    public org.glowroot.agent.shaded.google.api.ServiceOrBuilder getServiceConfigOrBuilder() {
      if (serviceConfigBuilder_ != null) {
        return serviceConfigBuilder_.getMessageOrBuilder();
      } else {
        return serviceConfig_ == null ?
            org.glowroot.agent.shaded.google.api.Service.getDefaultInstance() : serviceConfig_;
      }
    }
    /**
     * <pre>
     * The service configuration resource.
     * </pre>
     *
     * <code>.google.api.Service service_config = 2;</code>
     */
    private org.glowroot.agent.shaded.google.protobuf.SingleFieldBuilderV3<
        org.glowroot.agent.shaded.google.api.Service, org.glowroot.agent.shaded.google.api.Service.Builder, org.glowroot.agent.shaded.google.api.ServiceOrBuilder> 
        getServiceConfigFieldBuilder() {
      if (serviceConfigBuilder_ == null) {
        serviceConfigBuilder_ = new org.glowroot.agent.shaded.google.protobuf.SingleFieldBuilderV3<
            org.glowroot.agent.shaded.google.api.Service, org.glowroot.agent.shaded.google.api.Service.Builder, org.glowroot.agent.shaded.google.api.ServiceOrBuilder>(
                getServiceConfig(),
                getParentForChildren(),
                isClean());
        serviceConfig_ = null;
      }
      return serviceConfigBuilder_;
    }
    public final Builder setUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.api.servicemanagement.v1.CreateServiceConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:google.api.servicemanagement.v1.CreateServiceConfigRequest)
  private static final org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest();
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.glowroot.agent.shaded.google.protobuf.Parser<CreateServiceConfigRequest>
      PARSER = new org.glowroot.agent.shaded.google.protobuf.AbstractParser<CreateServiceConfigRequest>() {
    public CreateServiceConfigRequest parsePartialFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
        return new CreateServiceConfigRequest(input, extensionRegistry);
    }
  };

  public static org.glowroot.agent.shaded.google.protobuf.Parser<CreateServiceConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.glowroot.agent.shaded.google.protobuf.Parser<CreateServiceConfigRequest> getParserForType() {
    return PARSER;
  }

  public org.glowroot.agent.shaded.google.api.servicemanagement.v1.CreateServiceConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

