// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package org.glowroot.agent.shaded.google.api.servicemanagement.v1;

/**
 * <pre>
 * Request message for GetServiceConfig method.
 * </pre>
 *
 * Protobuf type {@code google.api.servicemanagement.v1.GetServiceConfigRequest}
 */
public  final class GetServiceConfigRequest extends
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.servicemanagement.v1.GetServiceConfigRequest)
    GetServiceConfigRequestOrBuilder {
  // Use GetServiceConfigRequest.newBuilder() to construct.
  private GetServiceConfigRequest(org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetServiceConfigRequest() {
    serviceName_ = "";
    configId_ = "";
  }

  @java.lang.Override
  public final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetServiceConfigRequest(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            configId_ = s;
            break;
          }
        }
      }
    } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor;
  }

  protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.Builder.class);
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceName_;
  /**
   * <pre>
   * The name of the service.  See the [overview](/service-management/overview)
   * for naming requirements.  For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the service.  See the [overview](/service-management/overview)
   * for naming requirements.  For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object configId_;
  /**
   * <code>string config_id = 2;</code>
   */
  public java.lang.String getConfigId() {
    java.lang.Object ref = configId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configId_ = s;
      return s;
    }
  }
  /**
   * <code>string config_id = 2;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getConfigIdBytes() {
    java.lang.Object ref = configId_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configId_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.glowroot.agent.shaded.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceNameBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (!getConfigIdBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 2, configId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceNameBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (!getConfigIdBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(2, configId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest)) {
      return super.equals(obj);
    }
    org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest other = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest) obj;

    boolean result = true;
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && getConfigId()
        .equals(other.getConfigId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + CONFIG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConfigId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(byte[] data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      byte[] data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for GetServiceConfig method.
   * </pre>
   *
   * Protobuf type {@code google.api.servicemanagement.v1.GetServiceConfigRequest}
   */
  public static final class Builder extends
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.servicemanagement.v1.GetServiceConfigRequest)
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequestOrBuilder {
    public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor;
    }

    protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.Builder.class);
    }

    // Construct using org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serviceName_ = "";

      configId_ = "";

      return this;
    }

    public org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest getDefaultInstanceForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.getDefaultInstance();
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest build() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest buildPartial() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest result = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest(this);
      result.serviceName_ = serviceName_;
      result.configId_ = configId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.glowroot.agent.shaded.google.protobuf.Message other) {
      if (other instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest) {
        return mergeFrom((org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest other) {
      if (other == org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getConfigId().isEmpty()) {
        configId_ = other.configId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the service.  See the [overview](/service-management/overview)
     * for naming requirements.  For example: `example.googleapis.com`.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceNameBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object configId_ = "";
    /**
     * <code>string config_id = 2;</code>
     */
    public java.lang.String getConfigId() {
      java.lang.Object ref = configId_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string config_id = 2;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getConfigIdBytes() {
      java.lang.Object ref = configId_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configId_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string config_id = 2;</code>
     */
    public Builder setConfigId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      configId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string config_id = 2;</code>
     */
    public Builder clearConfigId() {
      
      configId_ = getDefaultInstance().getConfigId();
      onChanged();
      return this;
    }
    /**
     * <code>string config_id = 2;</code>
     */
    public Builder setConfigIdBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      configId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.api.servicemanagement.v1.GetServiceConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:google.api.servicemanagement.v1.GetServiceConfigRequest)
  private static final org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest();
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.glowroot.agent.shaded.google.protobuf.Parser<GetServiceConfigRequest>
      PARSER = new org.glowroot.agent.shaded.google.protobuf.AbstractParser<GetServiceConfigRequest>() {
    public GetServiceConfigRequest parsePartialFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
        return new GetServiceConfigRequest(input, extensionRegistry);
    }
  };

  public static org.glowroot.agent.shaded.google.protobuf.Parser<GetServiceConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.glowroot.agent.shaded.google.protobuf.Parser<GetServiceConfigRequest> getParserForType() {
    return PARSER;
  }

  public org.glowroot.agent.shaded.google.api.servicemanagement.v1.GetServiceConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

