// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package org.glowroot.agent.shaded.google.api.servicemanagement.v1;

/**
 * <pre>
 * Response message for ListServiceRollouts method.
 * </pre>
 *
 * Protobuf type {@code google.api.servicemanagement.v1.ListServiceRolloutsResponse}
 */
public  final class ListServiceRolloutsResponse extends
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.servicemanagement.v1.ListServiceRolloutsResponse)
    ListServiceRolloutsResponseOrBuilder {
  // Use ListServiceRolloutsResponse.newBuilder() to construct.
  private ListServiceRolloutsResponse(org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListServiceRolloutsResponse() {
    rollouts_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  @java.lang.Override
  public final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ListServiceRolloutsResponse(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              rollouts_ = new java.util.ArrayList<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout>();
              mutable_bitField0_ |= 0x00000001;
            }
            rollouts_.add(
                input.readMessage(org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nextPageToken_ = s;
            break;
          }
        }
      }
    } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        rollouts_ = java.util.Collections.unmodifiableList(rollouts_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor;
  }

  protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ROLLOUTS_FIELD_NUMBER = 1;
  private java.util.List<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout> rollouts_;
  /**
   * <pre>
   * The list of rollout resources.
   * </pre>
   *
   * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
   */
  public java.util.List<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout> getRolloutsList() {
    return rollouts_;
  }
  /**
   * <pre>
   * The list of rollout resources.
   * </pre>
   *
   * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
   */
  public java.util.List<? extends org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder> 
      getRolloutsOrBuilderList() {
    return rollouts_;
  }
  /**
   * <pre>
   * The list of rollout resources.
   * </pre>
   *
   * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
   */
  public int getRolloutsCount() {
    return rollouts_.size();
  }
  /**
   * <pre>
   * The list of rollout resources.
   * </pre>
   *
   * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
   */
  public org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout getRollouts(int index) {
    return rollouts_.get(index);
  }
  /**
   * <pre>
   * The list of rollout resources.
   * </pre>
   *
   * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
   */
  public org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder getRolloutsOrBuilder(
      int index) {
    return rollouts_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object nextPageToken_;
  /**
   * <pre>
   * The token of the next page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      org.glowroot.agent.shaded.google.protobuf.ByteString bs = 
          (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The token of the next page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  public org.glowroot.agent.shaded.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      org.glowroot.agent.shaded.google.protobuf.ByteString b = 
          org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.glowroot.agent.shaded.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rollouts_.size(); i++) {
      output.writeMessage(1, rollouts_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextPageToken_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rollouts_.size(); i++) {
      size += org.glowroot.agent.shaded.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rollouts_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      size += org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextPageToken_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse)) {
      return super.equals(obj);
    }
    org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse other = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse) obj;

    boolean result = true;
    result = result && getRolloutsList()
        .equals(other.getRolloutsList());
    result = result && getNextPageToken()
        .equals(other.getNextPageToken());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRolloutsCount() > 0) {
      hash = (37 * hash) + ROLLOUTS_FIELD_NUMBER;
      hash = (53 * hash) + getRolloutsList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      org.glowroot.agent.shaded.google.protobuf.ByteString data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(byte[] data)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      byte[] data,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseDelimitedFrom(
      java.io.InputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parseFrom(
      org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for ListServiceRollouts method.
   * </pre>
   *
   * Protobuf type {@code google.api.servicemanagement.v1.ListServiceRolloutsResponse}
   */
  public static final class Builder extends
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.servicemanagement.v1.ListServiceRolloutsResponse)
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponseOrBuilder {
    public static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor;
    }

    protected org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.class, org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.Builder.class);
    }

    // Construct using org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRolloutsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (rolloutsBuilder_ == null) {
        rollouts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rolloutsBuilder_.clear();
      }
      nextPageToken_ = "";

      return this;
    }

    public org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ServiceManagerProto.internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse getDefaultInstanceForType() {
      return org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.getDefaultInstance();
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse build() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse buildPartial() {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse result = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (rolloutsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rollouts_ = java.util.Collections.unmodifiableList(rollouts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rollouts_ = rollouts_;
      } else {
        result.rollouts_ = rolloutsBuilder_.build();
      }
      result.nextPageToken_ = nextPageToken_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        org.glowroot.agent.shaded.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(org.glowroot.agent.shaded.google.protobuf.Message other) {
      if (other instanceof org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse) {
        return mergeFrom((org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse other) {
      if (other == org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse.getDefaultInstance()) return this;
      if (rolloutsBuilder_ == null) {
        if (!other.rollouts_.isEmpty()) {
          if (rollouts_.isEmpty()) {
            rollouts_ = other.rollouts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRolloutsIsMutable();
            rollouts_.addAll(other.rollouts_);
          }
          onChanged();
        }
      } else {
        if (!other.rollouts_.isEmpty()) {
          if (rolloutsBuilder_.isEmpty()) {
            rolloutsBuilder_.dispose();
            rolloutsBuilder_ = null;
            rollouts_ = other.rollouts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rolloutsBuilder_ = 
              org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRolloutsFieldBuilder() : null;
          } else {
            rolloutsBuilder_.addAllMessages(other.rollouts_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout> rollouts_ =
      java.util.Collections.emptyList();
    private void ensureRolloutsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        rollouts_ = new java.util.ArrayList<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout>(rollouts_);
        bitField0_ |= 0x00000001;
       }
    }

    private org.glowroot.agent.shaded.google.protobuf.RepeatedFieldBuilderV3<
        org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder, org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder> rolloutsBuilder_;

    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public java.util.List<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout> getRolloutsList() {
      if (rolloutsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rollouts_);
      } else {
        return rolloutsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public int getRolloutsCount() {
      if (rolloutsBuilder_ == null) {
        return rollouts_.size();
      } else {
        return rolloutsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout getRollouts(int index) {
      if (rolloutsBuilder_ == null) {
        return rollouts_.get(index);
      } else {
        return rolloutsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder setRollouts(
        int index, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout value) {
      if (rolloutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolloutsIsMutable();
        rollouts_.set(index, value);
        onChanged();
      } else {
        rolloutsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder setRollouts(
        int index, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder builderForValue) {
      if (rolloutsBuilder_ == null) {
        ensureRolloutsIsMutable();
        rollouts_.set(index, builderForValue.build());
        onChanged();
      } else {
        rolloutsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder addRollouts(org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout value) {
      if (rolloutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolloutsIsMutable();
        rollouts_.add(value);
        onChanged();
      } else {
        rolloutsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder addRollouts(
        int index, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout value) {
      if (rolloutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolloutsIsMutable();
        rollouts_.add(index, value);
        onChanged();
      } else {
        rolloutsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder addRollouts(
        org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder builderForValue) {
      if (rolloutsBuilder_ == null) {
        ensureRolloutsIsMutable();
        rollouts_.add(builderForValue.build());
        onChanged();
      } else {
        rolloutsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder addRollouts(
        int index, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder builderForValue) {
      if (rolloutsBuilder_ == null) {
        ensureRolloutsIsMutable();
        rollouts_.add(index, builderForValue.build());
        onChanged();
      } else {
        rolloutsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder addAllRollouts(
        java.lang.Iterable<? extends org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout> values) {
      if (rolloutsBuilder_ == null) {
        ensureRolloutsIsMutable();
        org.glowroot.agent.shaded.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rollouts_);
        onChanged();
      } else {
        rolloutsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder clearRollouts() {
      if (rolloutsBuilder_ == null) {
        rollouts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rolloutsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public Builder removeRollouts(int index) {
      if (rolloutsBuilder_ == null) {
        ensureRolloutsIsMutable();
        rollouts_.remove(index);
        onChanged();
      } else {
        rolloutsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder getRolloutsBuilder(
        int index) {
      return getRolloutsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder getRolloutsOrBuilder(
        int index) {
      if (rolloutsBuilder_ == null) {
        return rollouts_.get(index);  } else {
        return rolloutsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public java.util.List<? extends org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder> 
         getRolloutsOrBuilderList() {
      if (rolloutsBuilder_ != null) {
        return rolloutsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rollouts_);
      }
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder addRolloutsBuilder() {
      return getRolloutsFieldBuilder().addBuilder(
          org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder addRolloutsBuilder(
        int index) {
      return getRolloutsFieldBuilder().addBuilder(
          index, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of rollout resources.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Rollout rollouts = 1;</code>
     */
    public java.util.List<org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder> 
         getRolloutsBuilderList() {
      return getRolloutsFieldBuilder().getBuilderList();
    }
    private org.glowroot.agent.shaded.google.protobuf.RepeatedFieldBuilderV3<
        org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder, org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder> 
        getRolloutsFieldBuilder() {
      if (rolloutsBuilder_ == null) {
        rolloutsBuilder_ = new org.glowroot.agent.shaded.google.protobuf.RepeatedFieldBuilderV3<
            org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout, org.glowroot.agent.shaded.google.api.servicemanagement.v1.Rollout.Builder, org.glowroot.agent.shaded.google.api.servicemanagement.v1.RolloutOrBuilder>(
                rollouts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        rollouts_ = null;
      }
      return rolloutsBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <pre>
     * The token of the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        org.glowroot.agent.shaded.google.protobuf.ByteString bs =
            (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The token of the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public org.glowroot.agent.shaded.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        org.glowroot.agent.shaded.google.protobuf.ByteString b = 
            org.glowroot.agent.shaded.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (org.glowroot.agent.shaded.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The token of the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The token of the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder clearNextPageToken() {
      
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The token of the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder setNextPageTokenBytes(
        org.glowroot.agent.shaded.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final org.glowroot.agent.shaded.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.api.servicemanagement.v1.ListServiceRolloutsResponse)
  }

  // @@protoc_insertion_point(class_scope:google.api.servicemanagement.v1.ListServiceRolloutsResponse)
  private static final org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse();
  }

  public static org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.glowroot.agent.shaded.google.protobuf.Parser<ListServiceRolloutsResponse>
      PARSER = new org.glowroot.agent.shaded.google.protobuf.AbstractParser<ListServiceRolloutsResponse>() {
    public ListServiceRolloutsResponse parsePartialFrom(
        org.glowroot.agent.shaded.google.protobuf.CodedInputStream input,
        org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.glowroot.agent.shaded.google.protobuf.InvalidProtocolBufferException {
        return new ListServiceRolloutsResponse(input, extensionRegistry);
    }
  };

  public static org.glowroot.agent.shaded.google.protobuf.Parser<ListServiceRolloutsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public org.glowroot.agent.shaded.google.protobuf.Parser<ListServiceRolloutsResponse> getParserForType() {
    return PARSER;
  }

  public org.glowroot.agent.shaded.google.api.servicemanagement.v1.ListServiceRolloutsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

