// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package org.glowroot.agent.shaded.google.api.servicemanagement.v1;

public interface UndeleteServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.servicemanagement.v1.UndeleteServiceRequest)
    org.glowroot.agent.shaded.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the service. See the [overview](/service-management/overview)
   * for naming requirements. For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * The name of the service. See the [overview](/service-management/overview)
   * for naming requirements. For example: `example.googleapis.com`.
   * </pre>
   *
   * <code>string service_name = 1;</code>
   */
  org.glowroot.agent.shaded.google.protobuf.ByteString
      getServiceNameBytes();
}
