// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicecontrol/v1/check_error.proto

package org.glowroot.agent.shaded.google.api.servicecontrol.v1;

public final class CheckErrorProto {
  private CheckErrorProto() {}
  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.glowroot.agent.shaded.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final org.glowroot.agent.shaded.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicecontrol_v1_CheckError_descriptor;
  static final 
    org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicecontrol_v1_CheckError_fieldAccessorTable;

  public static org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.google/api/servicecontrol/v1/check_err" +
      "or.proto\022\034google.api.servicecontrol.v1\032\034" +
      "google/api/annotations.proto\"\202\004\n\nCheckEr" +
      "ror\022;\n\004code\030\001 \001(\0162-.google.api.serviceco" +
      "ntrol.v1.CheckError.Code\022\016\n\006detail\030\002 \001(\t" +
      "\"\246\003\n\004Code\022\032\n\026ERROR_CODE_UNSPECIFIED\020\000\022\r\n" +
      "\tNOT_FOUND\020\005\022\025\n\021PERMISSION_DENIED\020\007\022\026\n\022R" +
      "ESOURCE_EXHAUSTED\020\010\022\031\n\025SERVICE_NOT_ACTIV" +
      "ATED\020h\022\024\n\020BILLING_DISABLED\020k\022\023\n\017PROJECT_" +
      "DELETED\020l\022\023\n\017PROJECT_INVALID\020r\022\026\n\022IP_ADD",
      "RESS_BLOCKED\020m\022\023\n\017REFERER_BLOCKED\020n\022\026\n\022C" +
      "LIENT_APP_BLOCKED\020o\022\023\n\017API_KEY_INVALID\020i" +
      "\022\023\n\017API_KEY_EXPIRED\020p\022\025\n\021API_KEY_NOT_FOU" +
      "ND\020q\022!\n\034NAMESPACE_LOOKUP_UNAVAILABLE\020\254\002\022" +
      "\037\n\032SERVICE_STATUS_UNAVAILABLE\020\255\002\022\037\n\032BILL" +
      "ING_STATUS_UNAVAILABLE\020\256\002B\204\001\n org.glowroot.agent.shaded.google" +
      ".api.servicecontrol.v1B\017CheckErrorProtoP" +
      "\001ZJgoogle.golang.org/genproto/googleapis" +
      "/api/servicecontrol/v1;servicecontrol\370\001\001" +
      "b\006proto3"
    };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.glowroot.agent.shaded.google.protobuf.ExtensionRegistry assignDescriptors(
              org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.glowroot.agent.shaded.google.protobuf.Descriptors.FileDescriptor[] {
          org.glowroot.agent.shaded.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_google_api_servicecontrol_v1_CheckError_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_servicecontrol_v1_CheckError_fieldAccessorTable = new
      org.glowroot.agent.shaded.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicecontrol_v1_CheckError_descriptor,
        new java.lang.String[] { "Code", "Detail", });
    org.glowroot.agent.shaded.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
